### ISSUE TITLE
Doesn't support validation

### ISSUE THREAD

**Issue by neuzaluis** [KimPaow/sanity-color-list#4]
Hi :) ,
I noticed that I cannot validate the color-list :/
Is there anyway that you can help me?
```
{
        name: 'color',
        title: 'Color',
        type: 'colors', 
        validation: Rule => Rule.required(),
        options: {
          list: [
            { title: 'Blue', value: '#00b8ff' },
            { title: 'Yellow', value: '#ffe700' },
          ],
        },
      },
```

**Comment by KimPaow** [comment]
Thanks for letting me know! I'm a bit busy atm but will push an update when things clear up. If it's urgent all PR's are more than welcome :)

**Comment by arlenpeiffer** [comment]
running into a issue with the required validation as well. would love to see this implemented 👍

**Comment by KimPaow** [comment]
@arlenpeiffer Yeah I've noticed this issue too and tried to resolve it for some time now. It shows up when you nest the colorlist type. For example when you create a "colors" object type and then use that type instead of directly using the "colorlist" type. My best guess so far is that either there is a bug within the Studio itself with nested objects, or the data is not being saved correctly from my end. I'm trying to start a conversation with the Sanity team to figure out what's going on. 

Version `1.2.1` does not have this issue so until resolved I would recommend you to use that version instead.

**Comment by rexxars** [comment]
I've looked into this a bit and found the cause of the bug. Submitted a PR to fix the issue in Sanity: https://github.com/sanity-io/sanity/pull/2247

**Comment by rexxars** [comment]
This was fixed in v2.2.3 of Sanity!

**Comment by arlenpeiffer** [comment]
So awesome! Thanks @rexxars !

**Comment by rennehir** [comment]
This issue still seems to happen, when using the object notation for the value.

Only the option "Pink" from the example gives the validation error `Value did not match any allowed values`.

```javascript
{
  title: "Color List",
  description: "Pick a color",
  name: "colors",
  type: "colorlist", // required
  options: {
    list: [
      { title: "Yellow", value: "rgba(245, 199, 1, 0.5)" },
      { title: "Pink", value: {r: 246, g: 206, b: 219} }, // <--- This is the only one that is not accepted
      { title: "Red", value: "#f16d70" },
      { title: "Teal", value: "#88c6db" },
      { title: "Purple", value: "#aca0cc" },
      { title: "Green", value: "#bdcdcb" },
      { title: "White", value: "white" }
    ]
  }
},
```

Might it be related to the Studio comparing the object against the derived string value?

**Comment by rexxars** [comment]
> This issue still seems to happen, when using the object notation for the value.

Good find. The schema is defined as `value` being a string, which is why the validation fails. I think the object form should be removed from the readme, but I don't have access to this repo. @KimPaow ?

**Comment by KimPaow** [comment]
Wow sorry for the lack of replies from my end on this, I seem to have somehow missed new notifications for this issue. 

Thanks for the great work, @rexxars, I will try this out locally against the new studio version asap and update docs. :)
